name: Publish packages

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*.*"

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Build packages
        run: python -m build --outdir dist/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
            dist/*.zip
          prerelease: ${{ contains(github.ref, 'dev') || contains(github.ref, 'pre') }}