name: Release
on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: pip install build bump2version
      - name: Build packages
        run: python -m build --outdir dist/
      - name: Bump version
        id: apply_tags
        run: |
          git config --global user.email "github+actions@gmail.com"
          git config --global user.name "Actions"
          bump2version patch --allow-dirty
          git push --follow-tags
          echo ::set-output name=release_tag::$(git tag --points-at HEAD | grep '^v' | sort -nr | head -n1)
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl
          tag_name: ${{ steps.apply_tags.outputs.release_tag }}
