name: Release
on:
  workflow_dispatch:
    inputs:
      verson_part:
        description: "Part of the version to bump."
        required: true
        default: dev
        type: choice
        options:
          - dev
          - patch
          - minor
          - major

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: pip install bump2version tox tox-gh-actions
      - name: Bump version
        id: apply_tags
        run: |
          git config --global user.email "github+actions@gmail.com"
          git config --global user.name "Actions"
          bump2version "${BUMPED_VERSION_PART}"
        env:
          BUMPED_VERSION_PART: ${{ github.event.inputs.verson_part }}
      - name: Run tests
        run: tox
      - name: Push git tags
        run: |
          git config --global user.email "github+actions@gmail.com"
          git config --global user.name "Actions"
          git push --follow-tags
          echo ::set-output name=release_tag::$(git tag --points-at HEAD | grep '^v' | sort -nr | head -n1)
  publish-package:
    runs-on: ubuntu-latest
    needs: tag-release
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{needs.tag-release.outputs.release_tag}}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Build packages
        run: |
          pip install build
          python -m build --outdir dist/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
            dist/*.zip
          prerelease: ${{ contains(github.ref, 'dev') || contains(github.ref, 'pre') }}