name: Release
on:
  push:
    tags:
      - v*

jobs:
  test:
    uses: "./.github/workflows/main.yml"
  publish-package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Version number
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/:1}" >> $GITHUB_ENV # `:}"` -- same as 'tag' but without the 'v' prefix
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Build packages
        run: |
          pip install build
          python -m build --outdir dist/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
            dist/*.zip
          prerelease: ${{ contains(env.RELEASE_VERSION, 'dev') || contains(env.RELEASE_VERSION, 'pre') }}
          name: ${{env.RELEASE_VERSION}}
          tag_name: ${{env.RELEASE_VERSION}}