name: Release
on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  # test:
  #   uses: "./.github/workflows/main.yml"
  publish-package:
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Version number
        # run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/:1}" >> $GITHUB_ENV # `:}"` -- same as 'tag' but without the 'v' prefix
        run: |
          echo "RELEASE_VERSION=0.12.8" >> $GITHUB_ENV # `:}"` -- same as 'tag' but without the 'v' prefix
          echo "Release version: ${RELEASE_VERSION}"
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Build packages
        run: |
          pip install build
          python -m build --outdir dist/
          # XXX: Generate legacy names (TODO: fix version check code in the plugin)
          echo "s/-${RELEASE_VERSION}/-v${RELEASE_VERSION}/"
          cd dist && for l in $(ls -1 .); do cp $l $(echo $l | sed -e "s/-${RELEASE_VERSION}/-v${RELEASE_VERSION}/" ); done && cd ..
      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: |
      #       dist/*.whl
      #       dist/*.tar.gz
      #       dist/*.zip
      #     prerelease: ${{ contains(env.RELEASE_VERSION, 'dev') || contains(env.RELEASE_VERSION, 'pre') }}
      #     name: ${{env.RELEASE_VERSION}}
      #     tag_name: ${{env.RELEASE_VERSION}}